[platformio]
default_envs = rpipico2

[env:rpipico2]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipico2w
framework = arduino
board_build.core = earlephilhower
monitor_speed = 115200
build_flags =
    -DUSE_TINYUSB
    -I../../src
