"""Generate the one-bit LVGL Silkscreen Flat fonts used on the 160x128 display.

Requires Pillow. The source font and its OFL license live in assets/fonts/.
Run from the repository root: python3 tools/generate_silkscreen_fonts.py
"""

from pathlib import Path
import subprocess
from math import ceil

from PIL import Image, ImageDraw, ImageFont


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "assets/fonts/SilkscreenFlat-Regular.ttf"
OUTPUT = ROOT / "src/drivers/ui/silkscreen_pixel_fonts.c"
SIZES = (4, 5, 6, 7)
FIRST = 32
LAST = 126
THRESHOLD = 128
SOURCE_SIZE = 8
SOURCE_CAP_TOP = 4
SOURCE_CAP_HEIGHT = 5
GLYPH_HEIGHT = {4: 5, 5: 5, 6: 6, 7: 7}


def bitmap_and_metrics(font, codepoint, cap_height):
    char = chr(codepoint)
    source_width = max(1, ceil(font.getlength(char)))
    canvas = Image.new("L", (source_width, SOURCE_CAP_HEIGHT))
    ImageDraw.Draw(canvas).text((0, -SOURCE_CAP_TOP), char, font=font, fill=255)
    mask = canvas.resize((source_width, cap_height), Image.Resampling.NEAREST)
    width, height = mask.size
    active = [
        (x, y)
        for y in range(height)
        for x in range(width)
        if mask.getpixel((x, y)) >= THRESHOLD
    ]
    if not active:
        return [], (3 * 16, 0, 0, 0, 0)

    min_x = min(x for x, _ in active)
    max_x = max(x for x, _ in active)
    min_y = min(y for _, y in active)
    max_y = max(y for _, y in active)
    box_w = max_x - min_x + 1
    box_h = max_y - min_y + 1
    advance = (box_w + 1) * 16
    ofs_x = 0
    ofs_y = cap_height - max_y - 1
    bits = [
        int(mask.getpixel((x, y)) >= THRESHOLD)
        for y in range(min_y, max_y + 1)
        for x in range(min_x, max_x + 1)
    ]
    return bits, (advance, box_w, box_h, ofs_x, ofs_y)


def make_font(size):
    font = ImageFont.truetype(SOURCE, SOURCE_SIZE)
    cap_height = GLYPH_HEIGHT[size]
    packed = []
    glyphs = [(0, 0, 0, 0, 0, 0)]  # LVGL reserves glyph zero.
    for codepoint in range(FIRST, LAST + 1):
        bits, metrics = bitmap_and_metrics(font, codepoint, cap_height)
        index = len(packed)
        for offset in range(0, len(bits), 8):
            chunk = bits[offset : offset + 8]
            packed.append(sum(bit << (7 - pos) for pos, bit in enumerate(chunk)))
        glyphs.append((index, *metrics))

    name = f"silkscreen_flat_{size}"
    lines = [
        f"static const uint8_t {name}_bitmap[] = {{",
    ]
    for offset in range(0, len(packed), 16):
        values = ", ".join(f"0x{value:02x}" for value in packed[offset : offset + 16])
        lines.append(f"    {values},")
    lines.extend(
        [
            "};",
            f"static const lv_font_fmt_txt_glyph_dsc_t {name}_glyphs[] = {{",
        ]
    )
    for index, advance, box_w, box_h, ofs_x, ofs_y in glyphs:
        lines.append(
            "    { .bitmap_index = %d, .adv_w = %d, .box_w = %d, .box_h = %d, "
            ".ofs_x = %d, .ofs_y = %d },"
            % (index, advance, box_w, box_h, ofs_x, ofs_y)
        )
    lines.extend(
        [
            "};",
            f"static const lv_font_fmt_txt_cmap_t {name}_cmap[] = {{",
            "    { .range_start = 32, .range_length = 95, .glyph_id_start = 1,",
            "      .unicode_list = NULL, .glyph_id_ofs_list = NULL, .list_length = 0,",
            "      .type = LV_FONT_FMT_TXT_CMAP_FORMAT0_TINY },",
            "};",
            f"static const lv_font_fmt_txt_dsc_t {name}_dsc = {{",
            f"    .glyph_bitmap = {name}_bitmap,",
            f"    .glyph_dsc = {name}_glyphs,",
            f"    .cmaps = {name}_cmap,",
            "    .kern_dsc = NULL, .kern_scale = 0, .cmap_num = 1,",
            "    .bpp = 1, .kern_classes = 0, .bitmap_format = LV_FONT_FMT_TXT_PLAIN,",
            "    .stride = 0, .are_glyphs_dynamic_loaded = false,",
            "};",
            f"const lv_font_t {name} = {{",
            "    .get_glyph_dsc = lv_font_get_glyph_dsc_fmt_txt,",
            "    .get_glyph_bitmap = lv_font_get_bitmap_fmt_txt,",
            f"    .line_height = {cap_height + 1}, .base_line = 1,",
            "    .subpx = LV_FONT_SUBPX_NONE, .underline_position = -1,",
            "    .underline_thickness = 0, .static_bitmap = 1,",
            f"    .dsc = &{name}_dsc, .fallback = NULL, .user_data = NULL,",
            "};",
        ]
    )
    return lines


def main():
    lines = [
        "/* Generated by tools/generate_silkscreen_fonts.py from Silkscreen Flat (OFL). */",
        '#include "silkscreen_pixel_fonts.h"',
        "",
    ]
    for size in SIZES:
        lines.extend(make_font(size))
        lines.append("")
    OUTPUT.write_text("\n".join(lines))
    subprocess.run(["clang-format", "-i", str(OUTPUT)], check=True)


if __name__ == "__main__":
    main()
